### ISSUE TITLE
Add tenant Category and Description support, as well as Edit operation (OSOE-549)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Orchard-Core-API-Client#15]
In Orchard Core 1.6, Category and Description of tenant settings are also available via the API. So, let's add support to them.

Also, now we have an Edit operation in the API, so that should be supported too.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-549)

**Comment by Piedone** [comment]
@MZole Please check if the create/setup operation works with OC 1.5 as well (that doesn't have tenant Description/Category). If it does (i.e. it's backward compatible) then we can merge and release this without any special care.

**Comment by MZole** [comment]
Yes, it works and it doesn't raise any error or exception, the Description and Category are just ignored. (tested it with the 1.5 release branch of OC)

**Comment by Piedone** [comment]
Great then!
