### ISSUE TITLE
Remove CustomEditAsync (OSOE-646)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Orchard-Core-API-Client#30]
`IOrchardCoreApi.CustomEditAsync()` should never have been added, since it's about an endpoint for one of our own apps. Remove it, and instead, make it possible to utilize `ConfigurableCertificateValidatingHttpClientHandler` easily from 3rd-party API implementations too (or otherwise centralize token management and else that's in there).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-646)

**Comment by wAsnk** [comment]
Could you elaborate on this idea a bit more?

**Comment by Piedone** [comment]
What's your question, specifically?

**Comment by wAsnk** [comment]
Could you elaborate on how utilizing `ConfigurableCertificateValidatingHttpClientHandler` can keep the same logic for the current CustomEdit endpoint? That's a free extensibility point for anyone to implement in their app.

**Comment by Piedone** [comment]
`IOrchardCoreApi.CustomEditAsync()` is something that's not for a part of the OC API. It's a custom API endpoint that we needed for one particular use case in our own app, in some private module. This shouldn't be part of the open-source interface.

Rather, it should be implemented privately, and whatever else that needs to be done in this project to allow this to be done efficiently, with code re-use.
