### ISSUE TITLE
Remove obsolete property in TenantSetupApiModel during the next major release (OSOE-751)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/Orchard-Core-API-Client#34]
As discussed [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/460#issuecomment-1606232136).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-751)

**Comment by Piedone** [comment]
Was done in https://github.com/Lombiq/Orchard-Core-API-Client/commit/3a15ee025e50373282d81191cb7932fb61a9ccd2.
